### ISSUE TITLE
[3.1] Quick how-to if possible? Replacing Administrator Views

### ISSUE THREAD

**Issue by stevebauman** [orchestral/view#18]
I'm trying to follow the example located on your website here: http://orchestraplatform.com/docs/latest/components/view

But when I replace the files specified in the tutorial, nothing happens. I'm just looking to replace the administrator side theme completely. Are you able to just show a quick way of replacing the administrator views whenever you have a moment?

Thanks!

**Comment by crynobone** [comment]
Check out the installable theme.

    composer require stakie/adminlte-theme

**Comment by stevebauman** [comment]
Says could not find package unfortunately

**Comment by crynobone** [comment]
Sorry there a typo, it's actually `stackie/adminlte-theme`.

https://github.com/stackie/adminlte-theme

**Comment by stevebauman** [comment]
Awesome thanks!
