### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by parse-code** [orchestral/view#21]
I follow the tutorial here:  https://orchestraplatform.com/docs/3.3/components/view#basic-of-a-theme, but nothing happen.

**Comment by crynobone** [comment]
It is alive and being used for my projects, but I no longer pursue to advertise or promote to anyone.

**Comment by parse-code** [comment]
Thanks @crynobone , may I know the plan of the whole orchestra platform, will it keep develop?

**Comment by crynobone** [comment]
It will be updated to support upcoming Laravel releases but can't promise any active new features.
